# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jejumeet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jejumeet
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'Floaty', '~> 3.0.0'
  pod 'TLYShyNavBar'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Koyomi'
end
